language: python
python:
  - '3.4'
env:
  global:
    DJANGO_SECRET_KEY="Dummy django_secret_key"
    DEBUG=0
    DATABASE_URL="sqlite:///db.sqlite3"
    BACKLOG_CLIENT_ID="Dummy client_id"
    BACKLOG_CLIENT_SECRET="Dummy client_secret"
install:
  - pip install --upgrade pip
  - pip install Cython
  - pip install -r requirements.txt
script:
  - touch .env
deploy:
  provider: heroku
  buildpack: https://github.com/rivayama/heroku-buildpack-python
  api_key:
    secure: pUkqjm72YD9cPnRIfD98ProkPpXTapILNocu6w57trT2SJ6/B2LyPWmxSvToID7mnqDJiM82JecITtF2NfrtQJR/oX38WDTrPn7Ax+K6s8DU78NpGtx5TypS9VqYEiwZT1JTJl1A97S26U8VUR/TnnbaznlQlwso0oTfbcvTD9rAklvunZkGap2yhM8nR0ZSsP7ozayo87MbsDSUSou0YLKMYtZDjINBT5YTDHt9LmFX8Ish75o8G+6HZip5uCR5bTCdJw6qdpwXqWGoN9CD1HkDUOPBQ1edX+vwHjnXaqg1WxC+FRuptoNHWShSBM1QW7cty+Gnc0D3Pb8Dk5MqwuOwwhYPUuV8U9abZ4Z6uZHwPof84VCrlM1H98NZLD9fLEERp6LoHKWYfBKXOwiFRwMGYD04eq9x9PyafC8rSmY5M6xQGf6YcYDEi3Xml8JZHxUgKNDOqfOYmFjbtqLfc7KfXEzULyKLHT0e+BEu3ohiIGZQ9aR04Lqc6ljXhz0W7xPIyS2JRlxURoM35bX8EgQJkTzoqVxlJgL8DIEUh0O5VVTJ4VrmRMGUi7iPie5dFFISoBPclnnZ2AlCTWDQgI1ykcQhDSU72GCihyCYxKVtUeSDc3AcgnvtNcPREHGCPy4rlKxwBBpBCAeGdf5Lzsu0vbU33Io+ckvdU8Y13sY=
  run: "python manage.py migrate"
  app: projectautograder
  on:
    repo: rivayama/pag
